# This is a workflow to publish new package on npm after github release

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  release:
    types: [published]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run test-lib
        env:
          TZ: Europe/Zurich

  build:
    name: Build lib
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build-lib

  publish:
    name: Publish on npm
    needs: [test, build]
    runs-on: ubuntu-latest
    env:
      dist-directory: ./dist/lakto/horo/
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    # additional if condition: compare tag with package.json version
    # - name: Get the version
    # id: get_version
    # run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    # --> solution from https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/td-p/31595
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build-lib
      - run: cd ${{env.dist-directory}} && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: smartlyio/github-release-notes-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

