# This is a workflow to publish new package on npm after github release

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  release:
    types: [published]

jobs:
  test-build:
    name: Run test and build lib (on each push)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run test-lib
      - run: npm run build-lib
        env:
          TZ: Europe/Zurich

  update_release_draft:
    name: Update release draft (on each push into master branch)
    needs: [test-build]
    runs-on: ubuntu-latest
    # Drafts your next Release notes as Pull Requests are merged into "master"
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  update_changelog:
    name: Update CHANGELOG (on each push into master branch and with each release)
    needs: [test-build, update_release_draft]
    runs-on: ubuntu-latest
    # Drafts your next Release notes as Pull Requests are merged into "master"
    if: github.ref == 'refs/heads/master' || github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Update CHANGELOG file using gren
      uses: lakto/gren-changelog-action@v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        options: '--override'
    - name: Commit CHANGELOG
      run: |
        git config --local user.email "github@milchkannen.ch"
        git config --local user.name "daschbot"
        git add CHANGELOG.md
        git commit -m "docs(changelog): Update CHANGELOG"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/next-release
        force: true

  publish:
    name: Publish to npm (on each published release)
    needs: [test-build]
    runs-on: ubuntu-latest
    env:
      dist-directory: ./dist/lakto/horo/
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Update CHANGELOG file using gren
        uses: lakto/gren-changelog-action@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          options: '--override'
      - name: Upload CHANGELOG to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: CHANGELOG.md
          tag: ${{ github.ref }}
          overwrite: true
      - run: npm install
      - run: npm run build-lib
      - name: Update version
        run: cp CHANGELOG.md ${{env.dist-directory}}/ && cd ${{env.dist-directory}} && npm version ${{github.ref}} --git-tag-version=false --commit-hooks=false
      - if: "github.event.release.prerelease"
        run: npm publish ${{env.dist-directory}} --tag rc --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - if: "!github.event.release.prerelease"
        run: npm publish ${{env.dist-directory}} --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
